# Generated by Django 4.2.5 on 2025-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("headshot", models.ImageField(blank=True, upload_to="authors/")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("writer", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "volume_number",
                    models.PositiveIntegerField(default=1, help_text="Volume number"),
                ),
                (
                    "issue_number",
                    models.PositiveIntegerField(default=1, help_text="Issue number"),
                ),
                (
                    "short_title",
                    models.SlugField(
                        blank=True,
                        help_text="Short URL-friendly version of the title",
                        max_length=100,
                    ),
                ),
                (
                    "preview_text",
                    models.TextField(
                        blank=True, help_text="Short preview or intro for the article"
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("op-ed", "Op-Ed"),
                            ("news", "News"),
                            ("features", "Features"),
                            ("other", "Other"),
                        ],
                        default="news",
                        max_length=50,
                    ),
                ),
                (
                    "doc_url",
                    models.TextField(
                        blank=True, help_text="Paste the full Google Doc URL here."
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        blank=True,
                        help_text="Auto-extracted from doc_url",
                        max_length=255,
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True, help_text="Fetched HTML content from Google Docs."
                    ),
                ),
                ("is_current_issue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="newsletter.author"
                    ),
                ),
            ],
        ),
    ]
