# Generated by Django 4.2.5 on 2025-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="article_type",
            field=models.CharField(
                choices=[
                    ("op-ed", "Op-Ed"),
                    ("news", "News"),
                    ("features", "Features"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="is_current_issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="issue_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="untitled", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="writer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_html",
            field=models.TextField(
                blank=True, help_text="Fetched HTML content from Google Docs."
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="doc_id",
            field=models.CharField(
                blank=True, help_text="Auto-extracted from doc_url", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="doc_url",
            field=models.TextField(
                blank=True, help_text="Paste the full Google Doc URL here."
            ),
        ),
    ]
