# Generated by Django 4.2.5 on 2025-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_author_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title_image",
            field=models.ImageField(blank=True, null=True, upload_to="article_titles/"),
        ),
    ]
