# Generated by Django 4.2.5 on 2025-02-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_article_article_type_article_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="preview_text",
            field=models.TextField(
                blank=True, help_text="Short preview or intro for the article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="short_title",
            field=models.SlugField(
                blank=True,
                help_text="Short URL-friendly version of the title",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="volume_number",
            field=models.PositiveIntegerField(default=1, help_text="Volume number"),
        ),
        migrations.AlterField(
            model_name="article",
            name="issue_number",
            field=models.PositiveIntegerField(default=1, help_text="Issue number"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
