# Generated by Django 5.2.8 on 2025-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_article_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order to display on current issue page (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Image to show on the current issue homepage', null=True, upload_to='article_previews/'),
        ),
    ]
