# Generated by Django 4.2.5 on 2025-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_article_preview_text_article_short_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("headshot", models.ImageField(blank=True, upload_to="authors/")),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="newsletter.author"
            ),
        ),
    ]
