# Generated by Django 4.2.5 on 2026-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_article_display_order_article_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hide_image_border",
            field=models.BooleanField(default=False),
        ),
    ]
