# Generated by Django 4.2.30 on 2026-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_add_hide_image_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_current_issue',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
